_target_: pytorch_lightning.Trainer

min_epochs: 1
max_epochs: 1000
enable_progress_bar: True
accelerator: auto
devices: 1
precision: 32
check_val_every_n_epoch: 1
gradient_clip_val: 10

# Interpolated
default_root_dir: ${paths.output_dir}
