_target_: src.models.nuflows.NeutrinoFlow

prior_weight: 1.0e-5

embed_conf:
  outp_dim: 32
  hddn_dim: 128
  num_blocks: 2
  nrm: layer

deepset_conf:
  pool_type: attn
  attn_type: mean
  outp_dim: 16
  feat_net_kwargs:
    outp_dim: 16
    num_blocks: 2
    hddn_dim: 128
    nrm: layer
  attn_net_kwargs:
    outp_dim: 2
    num_blocks: 2
    hddn_dim: 128
    nrm: layer
  post_net_kwargs:
    num_blocks: 2
    hddn_dim: 128
    nrm: layer

flow_conf:
  nstacks: 10
  param_func: cplng
  invrt_func: rqs
  net_kwargs:
    num_blocks: 2
    hddn_dim: 128
    nrm: layer
  rqs_kwargs:
    num_bins: 10
    tail_bound: 4
    tails: linear
  do_lu: true
  nrm: none

# Full configuration for the model optimizer
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1.0e-3
  weight_decay: 1.0e-4

# Config dicts to pass to utils and pytorch lightning
sched_conf:
  utils:
    name: cyclicwithwarmup
    epochs_per_cycle: 5
  lightning:
    monitor: valid/total_loss
    interval: step
    frequency: 1
